### ISSUE TITLE
I2C no need to be "root"

### ISSUE THREAD

**Issue by Teka101** [leon-anavi/rpi-examples#1]
Hi,

In the sample for HTU21D, you can check I2C values without be root:
- remove line "wiringPiSetup();" in "HTU21D_test.c"
- add your user in "i2c" group

Enjoy ! :)

**Comment by leon-anavi** [comment]
Hi @Teka101,

Thank you for your contribution. I have added your suggestion as a note to the README.

Best regards, Leon

**Comment by Teka101** [comment]
:+1:
