### ISSUE TITLE
Asking for username and password 

### ISSUE THREAD

**Issue by killeraloha** [leon-anavi/rpi-examples#4]
type the following commands to get the source code of the example for writing and reading data to the NFC cards and RFID tags:

cd ~
git clone https://github.com/leon-anavi/rpi-examples.git

after typing this it's asking me for username and password?
please help 
thank you

**Comment by leon-anavi** [comment]
Hi @killeraloha,

No, you don't need username or password to clone a git repository with HTTPS:

```
$ git clone https://github.com/leon-anavi/rpi-examples.git
Cloning into 'rpi-examples'...
remote: Counting objects: 301, done.
remote: Total 301 (delta 0), reused 0 (delta 0), pack-reused 301
Receiving objects: 100% (301/301), 66.28 KiB | 309.00 KiB/s, done.
Resolving deltas: 100% (90/90), done.
```

For details please refer to GitHub documentation about cloning a repository: https://help.github.com/articles/cloning-a-repository/

Best regards,
Leon
